### ISSUE TITLE
 Could not load type 'Microsoft.AspNetCore.Razor.Language.RazorTemplateEngine'

### ISSUE THREAD

**Issue by stephenjg24-git** [extent-framework/extentreports-csharp#141]
Hello,  

I have a C# solution that is .Net 4.8.

When I have Extent Report 4.0.3 it builds and executes and crates the reports without issue.

If I update to 4.1.0 I get the error:  Could not load type 'Microsoft.AspNetCore.Razor.Language.RazorTemplateEngine'

This error is when I call Report.Flush()

I have update all nugets except for "RazorEngine.NetCore" I haev this on version 2.2.6. Since this is not a CORE but it is .net4.8 I can not update to 3.1.0

Is there any fixes for this?
![2021-09-10_14-07-26](https://user-images.githubusercontent.com/37232254/132904940-4923fc0b-9c14-4671-b67e-83d0fde8c5a2.jpg)

**Comment by nahush-hombali** [comment]
I am seeing the same issue and have the exact same setup. Any fixes/workarounds would be helpful.

**Comment by SleeplessDeveloper** [comment]
two whole years and still no solution...

**Comment by anshooarora** [comment]
Hello @SleeplessDeveloper - can you check with the latest 5.0.1?  https://www.nuget.org/packages/ExtentReports

**Comment by SleeplessDeveloper** [comment]
@anshooarora I did... and i had to downgrade from 5.0.1 to 4.1.0 be able to resolve my issues.

**Comment by untoldstory69** [comment]
@anshooarora I am using the latest version of the extent report. I am getting the same exception in extent.flush();

I tried to downgrade to 4.1.0 but still having an issue. 

is there any resolution for this issue? 
`System.TypeLoadException
  HResult=0x80131522
  Message=Could not load type 'Microsoft.AspNetCore.Razor.Language.RazorTemplateEngine' from assembly 'Microsoft.AspNetCore.Razor.Language, Version=6.0.24.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
  Source=RazorEngine.NetCore
  StackTrace:
   at RazorEngine.Compilation.CompilerServiceBase.GetGeneratorResult(IEnumerable`1 namespaces, TypeContext context)
   at RazorEngine.Compilation.CompilerServiceBase.GetCodeCompileUnit(TypeContext context)
   at RazorEngine.Roslyn.CSharp.RoslynCompilerServiceBase.CompileType(TypeContext context)
   at RazorEngine.Templating.RazorEngineCore.CreateTemplateType(ITemplateSource razorTemplate, Type modelType)
   at RazorEngine.Templating.RazorEngineCore.Compile(ITemplateKey key, Type modelType)
   at RazorEngine.Templating.RazorEngineService.CompileAndCacheInternal(ITemplateKey key, Type modelType)
   at RazorEngine.Templating.RazorEngineService.GetCompiledTemplate(ITemplateKey key, Type modelType, Boolean compileOnCacheMiss)
   at RazorEngine.Templating.RazorEngineService.RunCompile(ITemplateKey key, TextWriter writer, Type modelType, Object model, DynamicViewBag viewBag)
   at RazorEngine.Templating.DynamicWrapperService.RunCompile(ITemplateKey key, TextWriter writer, Type modelType, Object model, DynamicViewBag viewBag)
   at RazorEngine.Templating.RazorEngineServiceExtensions.RunCompile(IRazorEngineService service, String name, TextWriter writer, Type modelType, Object model, DynamicViewBag viewBag)
   at RazorEngine.Templating.RazorEngineServiceExtensions.<>c__DisplayClass16_0.<RunCompile>b__0(TextWriter writer)
   at RazorEngine.Templating.RazorEngineServiceExtensions.WithWriter(Action`1 withWriter)
   at RazorEngine.Templating.RazorEngineServiceExtensions.RunCompile(IRazorEngineService service, String name, Type modelType, Object model, DynamicViewBag viewBag)
   at AventStack.ExtentReports.Reporter.ExtentSparkReporter.OnNext(ReportEntity value)
   at System.Reactive.Subjects.Subject`1.OnNext(T value)
   at AventStack.ExtentReports.Core.ReactiveSubject.Flush()
   at AventStack.ExtentReports.Core.AbstractProcessor.OnFlush()
   at AventStack.ExtentReports.ExtentReports.Flush()
   at Microsoft.Dynamics365.UIAutomation.Sample.Test_POC.Tests.AssemblyCleanup() in C:\Users\kishor.sharma\Source\Repos\Ki\EasyReproD365\Microsoft.Dynamics365.UIAutomation.Sample\Test_POC\UnitTest1.cs:line 110
`
Thanks

**Comment by SleeplessDeveloper** [comment]
@untoldstory69 what other packages are installed in your project's dependencies?

**Comment by untoldstory69** [comment]
> @untoldstory69 what other packages are installed in your project's dependencies?

@SleeplessDeveloper  I've used extentreport 3.1.0 and not it is working. Thanks for the reply.

**Comment by SleeplessDeveloper** [comment]
@untoldstory69 try upgrade extent reports to Version"4.1.0". And let me know if it solves your issue.

**Comment by untoldstory69** [comment]
@SleeplessDeveloper  I tried using 4.1.0 but I was having issue. But it is working fine with 3.1.0.

**Comment by cl-oalami** [comment]
This issue is still current, with 5.0.0, 5.0.1 and 5.0.2.

Same setup as [stephenjg24-git](https://github.com/stephenjg24-git) (OP), can only be resolved by switching to 3.1.0, is there any fix in any upcoming version ?
