### ISSUE TITLE
extent.Flush() is failing for all of my reporting tests.

### ISSUE THREAD

**Issue by lior277** [extent-framework/extentreports-csharp#166]
working lang c#
After updating NUnit3TestAdapter package from 4.3.1 to 4.4.0  I am getting exception at extent.Flush()
Here is the stack trace:
System.ArgumentException
  HResult=0x80070057
  Message=Expression of type 'CompiledRazorTemplates.Dynamic.RazorEngine_f3bdefe4093245f3900eab7bf2d014ca' cannot be used for return type 'RazorEngine.Templating.ITemplate'
  Source=System.Linq.Expressions
  StackTrace:
   at System.Linq.Expressions.Expression.ValidateLambdaArgs(Type delegateType, Expression& body, ReadOnlyCollection`1 parameters, String paramName)
   at System.Linq.Expressions.Expression.Lambda[TDelegate](Expression body, String name, Boolean tailCall, IEnumerable`1 parameters)
   at System.Linq.Expressions.Expression.Lambda[TDelegate](Expression body, Boolean tailCall, IEnumerable`1 parameters)
   at System.Linq.Expressions.Expression.Lambda[TDelegate](Expression body, ParameterExpression[] parameters)
   at RazorEngine.Templating.TypeLoader.GetConstructorInternal(Type type)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at RazorEngine.Templating.TypeLoader.GetConstructor(Type type)
   at RazorEngine.Templating.TypeLoader.CreateInstance(Type type)
   at RazorEngine.Templating.DefaultActivator.CreateInstance(InstanceContext context)
   at RazorEngine.Templating.RazorEngineCore.CreateTemplate(ICompiledTemplate template, Object model, DynamicViewBag viewbag)
   at RazorEngine.Templating.RazorEngineCore.<RunTemplate>d__12.MoveNext()
   at RazorEngine.Templating.RazorEngineService.Run(ITemplateKey key, TextWriter writer, Type modelType, Object model, DynamicViewBag viewBag)
   at RazorEngine.Templating.RazorEngineService.RunCompile(ITemplateKey key, TextWriter writer, Type modelType, Object model, DynamicViewBag viewBag)
   at RazorEngine.Templating.DynamicWrapperService.RunCompile(ITemplateKey key, TextWriter writer, Type modelType, Object model, DynamicViewBag viewBag)
   at RazorEngine.Templating.RazorEngineServiceExtensions.RunCompile(IRazorEngineService service, String name, TextWriter writer, Type modelType, Object model, DynamicViewBag viewBag)
   at RazorEngine.Templating.RazorEngineServiceExtensions.<>c__DisplayClass16_0.<RunCompile>b__0(TextWriter writer)
   at RazorEngine.Templating.RazorEngineServiceExtensions.WithWriter(Action`1 withWriter)
   at RazorEngine.Templating.RazorEngineServiceExtensions.RunCompile(IRazorEngineService service, String name, Type modelType, Object model, DynamicViewBag viewBag)
   at AventStack.ExtentReports.Reporter.ExtentHtmlReporter.Flush(ReportAggregates reportAggregates)
   at AventStack.ExtentReports.Core.ReportObservable.<>c__DisplayClass59_0.<NotifyReporters>b__0(IExtentReporter x)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at AventStack.ExtentReports.Core.ReportObservable.NotifyReporters()
   at AventStack.ExtentReports.Core.ReportObservable.Flush()
   at AventStack.ExtentReports.ExtentReports.Flush()
   at AirSoftAutomationFramework.Internals.DAL.Report.ReportsGenerationClass.AfterTest(IWebDriver driver) in C:\Users\Lior\Source\Repos\airsoftautomationframework\AirSoftAutomationFramework\Internals\DAL\Report\ReportsGenerationClass.cs:line 210

  This exception was originally thrown at this call stack:
    [External Code]
    AirSoftAutomationFramework.Internals.DAL.Report.ReportsGenerationClass.AfterTest(OpenQA.Selenium.IWebDriver) in ReportsGenerationClass.cs

**Comment by DD0DGE** [comment]
Did you get a resolution for this?  I am having the same issue with the Flush statement.  Thank you!

**Comment by lior277** [comment]
no, I am still waiting.
