### ISSUE TITLE
extent.Flush() thowing RazorEngine error

### ISSUE THREAD

**Issue by bzhechkov** [extent-framework/extentreports-csharp#167]
extent.Flush() was working fine with v4.1.0 for ages and recently started to fail with this: 

`System.ArgumentException
  HResult=0x80070057
  Message=Expression of type 'CompiledRazorTemplates.Dynamic.RazorEngine_059ef63a8d6748b1bdcc58bfe5871a11' cannot be used for return type 'RazorEngine.Templating.ITemplate'
  Source=System.Linq.Expressions
  StackTrace:
   at System.Linq.Expressions.Expression.ValidateLambdaArgs(Type delegateType, Expression& body, ReadOnlyCollection`1 parameters, String paramName)
   at System.Linq.Expressions.Expression.Lambda[TDelegate](Expression body, String name, Boolean tailCall, IEnumerable`1 parameters)
   at System.Linq.Expressions.Expression.Lambda[TDelegate](Expression body, Boolean tailCall, IEnumerable`1 parameters)
   at System.Linq.Expressions.Expression.Lambda[TDelegate](Expression body, ParameterExpression[] parameters)
   at RazorEngine.Templating.TypeLoader.GetConstructorInternal(Type type)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at RazorEngine.Templating.TypeLoader.GetConstructor(Type type)
   at RazorEngine.Templating.TypeLoader.CreateInstance(Type type)
   at RazorEngine.Templating.DefaultActivator.CreateInstance(InstanceContext context)
   at RazorEngine.Templating.RazorEngineCore.CreateTemplate(ICompiledTemplate template, Object model, DynamicViewBag viewbag)
   at RazorEngine.Templating.RazorEngineCore.<RunTemplate>d__12.MoveNext()
   at RazorEngine.Templating.RazorEngineService.Run(ITemplateKey key, TextWriter writer, Type modelType, Object model, DynamicViewBag viewBag)
   at RazorEngine.Templating.RazorEngineService.RunCompile(ITemplateKey key, TextWriter writer, Type modelType, Object model, DynamicViewBag viewBag)
   at RazorEngine.Templating.DynamicWrapperService.RunCompile(ITemplateKey key, TextWriter writer, Type modelType, Object model, DynamicViewBag viewBag)
   at RazorEngine.Templating.RazorEngineServiceExtensions.RunCompile(IRazorEngineService service, String name, TextWriter writer, Type modelType, Object model, DynamicViewBag viewBag)
   at RazorEngine.Templating.RazorEngineServiceExtensions.<>c__DisplayClass16_0.<RunCompile>b__0(TextWriter writer)
   at RazorEngine.Templating.RazorEngineServiceExtensions.WithWriter(Action`1 withWriter)
   at RazorEngine.Templating.RazorEngineServiceExtensions.RunCompile(IRazorEngineService service, String name, Type modelType, Object model, DynamicViewBag viewBag)
   at AventStack.ExtentReports.Reporter.ExtentHtmlReporter.Flush(ReportAggregates reportAggregates)
   at AventStack.ExtentReports.Core.ReportObservable.<>c__DisplayClass59_0.<NotifyReporters>b__0(IExtentReporter x)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at AventStack.ExtentReports.Core.ReportObservable.NotifyReporters()
   at AventStack.ExtentReports.Core.ReportObservable.Flush()
   at AventStack.ExtentReports.ExtentReports.Flush()`

**Comment by kais-khalifa** [comment]
I'm having the same issue. It works with Net48 but fails with net6 and net7
<img width="1352" alt="image" src="https://user-images.githubusercontent.com/85735928/224136856-1383ca79-4b78-43d7-ba99-61a084e56f07.png">
