### ISSUE TITLE
Error: Collection was modified; enumeration operation may not execute

### ISSUE THREAD

**Issue by mrybson** [extent-framework/extentreports-csharp#88]
**Version: 4.0.3**

When executing in parallel, we're sometimes getting the following exception:

**Error Message**
System.InvalidOperationException : Collection was modified; enumeration operation may not execute.

**Stacktrace**
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at AventStack.ExtentReports.Core.ReportStatusStats.UpdateGroupCountsBDD(Test test)
   at AventStack.ExtentReports.Core.ReportStatusStats.AddTestForStatusStatsUpdate(Test test)
   at AventStack.ExtentReports.Core.ReportStatusStats.<RefreshStats>b__146_0(Test x)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at AventStack.ExtentReports.Core.ReportStatusStats.RefreshStats()
   at AventStack.ExtentReports.Core.ReportStatusStats.Refresh(List`1 testList)
   at AventStack.ExtentReports.Core.ExtentObservable.RefreshReportStats()
   at AventStack.ExtentReports.Core.ExtentObservable.RefreshReportEntities()
   at AventStack.ExtentReports.Core.ExtentObservable.CollectRunInfo()
   at AventStack.ExtentReports.Core.ExtentObservable.AddLog(Test test, Log log)
   at AventStack.ExtentReports.ExtentTest.AddLog(Log evt)
   at AventStack.ExtentReports.ExtentTest.Log(Status status, String details, MediaEntityModelProvider provider)
   at AventStack.ExtentReports.ExtentTest.Pass(String details, MediaEntityModelProvider provider)
   at Tests.AcceptanceTesting.Helpers.Hooks.InsertReportingSteps(FeatureContext featureContext, ScenarioContext scenarioContext) in E:\Program F..

Please let me know if there's a workaround or if can be fixed

**Comment by NeelSM** [comment]
Hi, I am also facing same kind of issue, see the log below. This issue occurs during parallel execution and getting displayed for in random test scripts.

Issue in test execution: 
Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at CompiledRazorTemplates.Dynamic.RazorEngine_e71a8d1531fc466e8347d9374eea9efe.Execute()
   at RazorEngine.Templating.TemplateBase.RazorEngine.Templating.ITemplate.Run(ExecuteContext context, TextWriter reader)
   at RazorEngine.Templating.TemplateBase.<>c__DisplayClass32_0.b__0(TextWriter tw)
   at RazorEngine.Templating.TemplateWriter.WriteTo(TextWriter writer)
   at RazorEngine.Templating.TemplateBase.Write(TemplateWriter helper)
   at CompiledRazorTemplates.Dynamic.RazorEngine_c7c3a4a2f8f04c7ca3bf5dbd33cf9447.Execute()
   at RazorEngine.Templating.TemplateBase.RazorEngine.Templating.ITemplate.Run(ExecuteContext context, TextWriter reader)
   at RazorEngine.Templating.RazorEngineCore.RunTemplate(ICompiledTemplate template, TextWriter writer, Object model, DynamicViewBag viewBag)
   at RazorEngine.Templating.RazorEngineService.RunCompile(ITemplateKey key, TextWriter writer, Type modelType, Object model, DynamicViewBag viewBag)
   at RazorEngine.Templating.DynamicWrapperService.RunCompile(ITemplateKey key, TextWriter writer, Type modelType, Object model, DynamicViewBag viewBag)
   at RazorEngine.Templating.RazorEngineServiceExtensions.<>c__DisplayClass16_0.b__0(TextWriter writer)
   at RazorEngine.Templating.RazorEngineServiceExtensions.WithWriter(Action`1 withWriter)
   at RazorEngine.Templating.RazorEngineServiceExtensions.RunCompile(IRazorEngineService service, String name, Type modelType, Object model, DynamicViewBag viewBag)
   at AventStack.ExtentReports.Reporter.ExtentV3HtmlReporter.Flush(ReportAggregates reportAggregates)
   at AventStack.ExtentReports.Core.ExtentObservable.<>c__DisplayClass59_0.b__0(IExtentReporter x)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at AventStack.ExtentReports.Core.ExtentObservable.NotifyReporters()
   at AventStack.ExtentReports.Core.ExtentObservable.Flush()
   at AventStack.ExtentReports.ExtentReports.Flush()

Could please advice on this

**Comment by anshooarora** [comment]
Please check with version 4.1.0-alpha3.

**Comment by anshooarora** [comment]
@mrybson @NeelSM 

Can you please check with [4.1.0-alpha3](https://www.nuget.org/packages/ExtentReports/4.1.0-alpha3)?

**Comment by anshooarora** [comment]
[4.1.0-alpha4](https://www.nuget.org/packages/ExtentReports/4.1.0-alpha4) was just released as well. Please reopen if you continue to have this issue, thank you.
